git:
  depth: false # we need this to make proper releases

branches:
  only:
    - master
    - /^release\/.+$/
    - /^major\/.+$/

install: true
sudo: required

language: node_js
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - name: '@sentry/packages - build + lint + test + codecov + danger [node v8]'
      node_js: '8'
      script: scripts/danger.sh
    - name: '@sentry/packages - pack and zeus upload'
      node_js: '8'
      script: scripts/pack-and-upload.sh || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]
    - name: '@sentry/packages - build and test [node v6]'
      node_js: '6'
      script: scripts/test.sh
    - name: '@sentry/packages - build and test [node v10]'
      node_js: '10'
      script: scripts/test.sh
    - name: '@sentry/browser - integration tests'
      node_js: '8'
      addons:
        chrome: stable
        firefox: latest
      script: scripts/browser-integration.sh
    - name: '@sentry/browser - saucelabs tests'
      if: fork = false
      node_js: '8'
      addons:
        sauce_connect: true
      script: scripts/browser-saucelabs.sh
    - name: 'raven-js - unit and integration tests'
      node_js: '8'
      addons:
        chrome: stable
        firefox: latest
      script: scripts/raven-js.sh
    - name: 'raven-node [node v4]'
      node_js: '4'
      script: scripts/raven-node.sh
    - name: 'raven-node [node v6]'
      node_js: '6'
      script: scripts/raven-node.sh
    - name: 'raven-node [node v8]'
      node_js: '8'
      script: scripts/raven-node.sh
    - name: 'raven-node [node v10]'
      node_js: '10'
      script: scripts/raven-node.sh

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/853ee4aa-d692-11e7-8c60-0a580a28020f/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
