name: 'close stale issues/PRs'
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  stale:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/stale@6f05e4244c9a0b2ed3401882b05d701dd0a7289b
        with:
          repo-token: ${{ github.token }}
          days-before-stale: 21
          days-before-close: 7
          only-labels: ''
          operations-per-run: 100
          remove-stale-when-updated: true
          debug-only: false
          ascending: false

          exempt-issue-labels: 'Status: Backlog,Status: In Progress'
          stale-issue-label: 'Status: Stale'
          stale-issue-message: |-
            This issue has gone three weeks without activity. In another week, I will close it.

            But! If you comment or otherwise update it, I will reset the clock, and if you label it `Status: Backlog` or `Status: In Progress`, I will leave it alone ... forever!

            ----

            "A weed is but an unloved flower." â€• _Ella Wheeler Wilcox_ ðŸ¥€
          close-issue-label: ''
          close-issue-message: ''

          exempt-pr-labels: 'Status: Backlog,Status: In Progress'
          stale-pr-label: 'Status: Stale'
          stale-pr-message: |-
            This pull request has gone three weeks without activity. In another week, I will close it.

            But! If you comment or otherwise update it, I will reset the clock, and if you label it `Status: Backlog` or `Status: In Progress`, I will leave it alone ... forever!

            ----

            "A weed is but an unloved flower." â€• _Ella Wheeler Wilcox_ ðŸ¥€
          close-pr-label:
          close-pr-message: ''
